/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'almacenes': RouteRecordInfo<'almacenes', '/almacenes', Record<never, never>, Record<never, never>>,
    'caja-control': RouteRecordInfo<'caja-control', '/caja/control', Record<never, never>, Record<never, never>>,
    'caja-movimientos': RouteRecordInfo<'caja-movimientos', '/caja/movimientos', Record<never, never>, Record<never, never>>,
    'caja-reportes': RouteRecordInfo<'caja-reportes', '/caja/reportes', Record<never, never>, Record<never, never>>,
    'caja-sesiones': RouteRecordInfo<'caja-sesiones', '/caja/sesiones', Record<never, never>, Record<never, never>>,
    'categorias': RouteRecordInfo<'categorias', '/categorias', Record<never, never>, Record<never, never>>,
    'clientes': RouteRecordInfo<'clientes', '/clientes', Record<never, never>, Record<never, never>>,
    'clientes-cuentas': RouteRecordInfo<'clientes-cuentas', '/clientes/cuentas', Record<never, never>, Record<never, never>>,
    'compras': RouteRecordInfo<'compras', '/compras', Record<never, never>, Record<never, never>>,
    'compras-registrar': RouteRecordInfo<'compras-registrar', '/compras/registrar', Record<never, never>, Record<never, never>>,
    'conversion': RouteRecordInfo<'conversion', '/conversion', Record<never, never>, Record<never, never>>,
    'conversion-registrar': RouteRecordInfo<'conversion-registrar', '/conversion/registrar', Record<never, never>, Record<never, never>>,
    'devoluciones': RouteRecordInfo<'devoluciones', '/devoluciones', Record<never, never>, Record<never, never>>,
    'inventario-kardex': RouteRecordInfo<'inventario-kardex', '/inventario/kardex', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'productos': RouteRecordInfo<'productos', '/productos', Record<never, never>, Record<never, never>>,
    'productos-registrar': RouteRecordInfo<'productos-registrar', '/productos/registrar', Record<never, never>, Record<never, never>>,
    'proveedores': RouteRecordInfo<'proveedores', '/proveedores', Record<never, never>, Record<never, never>>,
    'roles-permisos': RouteRecordInfo<'roles-permisos', '/roles-permisos', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'sucursales': RouteRecordInfo<'sucursales', '/sucursales', Record<never, never>, Record<never, never>>,
    'tienda': RouteRecordInfo<'tienda', '/tienda', Record<never, never>, Record<never, never>>,
    'transportes': RouteRecordInfo<'transportes', '/transportes', Record<never, never>, Record<never, never>>,
    'transportes-registrar': RouteRecordInfo<'transportes-registrar', '/transportes/registrar', Record<never, never>, Record<never, never>>,
    'unidades': RouteRecordInfo<'unidades', '/unidades', Record<never, never>, Record<never, never>>,
    'usuarios': RouteRecordInfo<'usuarios', '/usuarios', Record<never, never>, Record<never, never>>,
    'ventas': RouteRecordInfo<'ventas', '/ventas', Record<never, never>, Record<never, never>>,
    'ventas-registrar': RouteRecordInfo<'ventas-registrar', '/ventas/registrar', Record<never, never>, Record<never, never>>,
  }
}
